spring:
  #redis配置
  data:
    redis:
      port: 6379
      host: 47.112.114.139
      database: 2
      password: 123456
  #数据库连接 - mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shiwujieai
    password: PbEbzPLk6XEDj3aC
    url: jdbc:mysql://47.112.114.139:3306/shiwujieai
