server:
  port: 8500
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  application:
    name: shiwujieAi
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: sk-6374b4a1ebd64f56ae8d0799e74b7927
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen3-max
    chat:
      client:
        enabled: true
# 明确指定日志配置
logging:
  config: classpath:logback-spring.xml
# searchApi
search-api:
  api-key: 4qkQ96eSGHAbAQKS5wbs8WyT
#dubbo配置
dubbo:
  application:
    name: shiwujie-ai
    logger: slf4j
    serialize-check-status: DISABLE
    qos-enable: false
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
    timeout: 5000
    password: nacos
    username: nacos
    parameters:
      empty-protection: true   # 关键：开启空保护