spring:
  #redis配置
  redis:
    port: 6379
    host: 43.139.38.62
    database: 2
    password: 123456
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shiwujieCommunity
    password: JRM582hhtidPtFrG
    url: jdbc:mysql://43.139.38.62:3306/shiwujiecommunity
# 打开mybatis的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 打开日志
logging:
  level:
    com.swj.shiwujie: DEBUG
    org.springframework.web.socket: DEBUG
