spring:
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1   # 本机调试时注册到 nacos 的 IP
# 打开mybatis的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 打开日志
logging:
  level:
    com.swj.shiwujie: DEBUG
    org.springframework.web.socket: DEBUG
