spring:
  cloud:
    gateway:
      routes:
    # 用户端转发
        - id: route_user
          uri: http://localhost:8200
          predicates:
            - Path=/api/user/**,/api/family/**
    # 视频转发配置
        - id: route_call
          uri: http://localhost:8124
          predicates:
            - Path=/api/channel/**,/api/callHelp/**
        # SockJS route
        - id: websocket_sockjs_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/websocket/**
        # Normal Websocket route
        - id: websocket_route
          uri: ws://localhost:8082
          predicates:
            - Path=/api/websocket/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

