spring:
  application:
    name: shiwujieGatewaty
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        # 用户端转发
        - id: route_user
          uri: http://localhost:8200
          predicates:
            - Path=/api/user/**
        # 视频转发配置
        - id: route_call
          uri: http://localhost:8300
          predicates:
            - Path=/api/call/**
        # SockJS route
        - id: websocket_sockjs_route
          uri: http://localhost:8350
          predicates:
            - Path=/api/ws/call
        # Normal Websocket route
        - id: websocket_route
          uri: ws://localhost:8350
          predicates:
            - Path=/api/ws/call
        # 社区转发配置
        - id: route_community
          uri: http://localhost:8400
          predicates:
            - Path=/api/community/**
        # 社区转发配置
        - id: route_ai
          uri: http://localhost:8500
          predicates:
            - Path=/api/ai/**
#  cloud:
#    gateway:
#      routes:
#        # 用户端转发
#        - id: route_user
#          uri: lb://shiwujie-user
#          predicates:
#            - Path=/api/user/**
#        # 视频转发配置
#        - id: route_call
#          uri: lb://shiwujie-call
#          predicates:
#            - Path=/api/call/**
#        # Normal Websocket route
#        - id: websocket_route
#          uri: lb:ws://shiwujie-call
#          predicates:
#            - Path=/api/ws/call
#        # 社区转发配置
#        - id: route_community
#          uri: lb://shiwujie-community
#          predicates:
#            - Path=/api/community/**
#        # 社区转发配置
#        - id: route_ai
#          uri: lb://shiwujie-ai
#          predicates:
#            - Path=/api/ai/**
server:
  servlet:
    context-path: /api  #  确保这里没有设置特殊的context-path
  port: 8100

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: user
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api/user/v2/api-docs?group=user
        service-name: user-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /
        order: 2
      - name: call
        url: /api/call/v2/api-docs?group=call
        service-name: order-service
        # 路由前缀
        context-path: /
        order: 3
      - name: community
        url: /api/community/v2/api-docs?group=community
        service-name: order-service
        # 路由前缀
        context-path: /
        order: 4




