spring:
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*:*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
    # 用户端转发
        - id: route_user
          uri: http://localhost:8200
          predicates:
            - Path=/api/user/**
    # 视频转发配置
        - id: route_call
          uri: http://localhost:8300
          predicates:
            - Path=/api/call/**
        # SockJS route
        - id: websocket_sockjs_route
          uri: http://localhost:8350
          predicates:
            - Path=/api/ws/call
        # Normal Websocket route
        - id: websocket_route
          uri: ws://localhost:8350
          predicates:
            - Path=/api/ws/call
    # 社区转发配置
        - id: route_community
          uri: http://localhost:8400
          predicates:
            - Path=/api/community/**
    # 社区转发配置
        - id: route_ai
          uri: http://localhost:8500
          predicates:
            - Path=/api/ai/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

